name: Thirst
version: '${project.version}'
main: com.reve.thirst.Main
api-version: 1.19
authors: [ doiche, crazywindow7 ]
description: thirst
commands:
  getmythirst:
    description: show your thirst level.
